apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustermonitor
  namespace: clustermonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustermonitor
  template:
    metadata:
      labels:
        app: clustermonitor
    spec:
      containers:
        - name: clustermonitor
          image: ghcr.io/willholt1/clustermonitor:1.0.0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: clustermonitor
  namespace: clustermonitor
spec:
  selector:
    app: clustermonitor
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clustermonitor
  namespace: clustermonitor
spec:
  rules:
    - host: clustermonitor.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clustermonitor
                port:
                  number: 80
